# Theme settings
# theme: "Academic" # You can change this to another Jekyll theme

remote_theme: "academic/academic"

# Markdown processing
markdown: kramdown

permalink: /:categories/:year/:month/:day/:title/

baseurl: "/Pranalyze"
