# Theme settings
theme: "jekyll-theme-Architect" # You can change this to another Jekyll theme

# Markdown processing
markdown: kramdown

permalink: /:categories/:year/:month/:day/:title/

baseurl: "/Pranalyze"
